services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    # O logging_collector agora aponta diretamente para a pasta mapeada
    command: >
      postgres
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgresql.log
      -c log_file_mode=0666
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
      - ./postgres/logs:/var/log/postgresql
      - ./postgres/conf:/etc/postgresql-custom
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak_service
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${DB_ADMIN_USER}
      KC_DB_PASSWORD: ${DB_ADMIN_PASSWORD}
      KC_HOSTNAME: localhost
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_LOG: file
      KC_LOG_FILE: /opt/keycloak/logs/keycloak.log
    volumes:
      - ./keycloak/conf:/opt/keycloak/conf
      - ./keycloak/logs:/opt/keycloak/logs
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
