# Configurações de Banco de Dados
db=postgres
db-url=jdbc:postgresql://postgres:5432/keycloak

# Configurações de Log
log=file
log-file=/opt/keycloak/logs/keycloak.log

# Configurações de HTTP/Rede
http-enabled=true
hostname-strict=false
